'use client';
import { createContext, useContext, useState, useEffect } from 'react';

const translations = {
    en: {
        login: 'Login',
        loginBtn: 'Login',
        logout: 'Logout',
        register: 'Register',
        signInToContinue: 'Sign in to continue',
        backToGuest: 'Back to Guest Portal',
        // Top Nav Categories
        organizationCategory: 'Organization',
        serviceCategory: 'Service',
        computerSettingsCategory: 'Computer Settings',
        systemCategory: 'System',
        ticketsCategory: 'Tickets',
        supportCategory: 'Support',
        // IT Sidebar
        itMenu: 'IT Menu',
        dashboardStats: '📊 Dashboard & Stats',
        requestBoard: '📋 Request Board',
        historyTickets: '🗄️ History Tickets',
        computerInventory: '💻 Computer Inventory',
        closeJobHistory: '✅ Close Job History',
        userApproval: 'User Approval',
        itUsersChat: '💬 IT / Users Chat',
        // IT Pages
        itDashboard: 'IT Dashboard',
        itRequestBoard: 'IT Request Board',
        closedJobHistory: 'Closed Job History',
        itSupportChat: 'IT Support Chat',
        // Admin Sidebar
        adminMenu: 'Admin Menu',
        dashboard: 'Dashboard',
        locations: 'Locations',
        companies: 'Companies',
        sites: 'Sites',
        departments: 'Departments',
        categories: 'Categories',
        manageUsers: 'Manage Users',
        manageTickets: 'Manage Tickets',
        deviceTypes: 'Device Types',
        operatingSystems: 'Operating Systems',
        msOffices: 'MS Offices',
        serviceLifeGroups: 'Service Life Groups',
        scriptInstallStatuses: 'Script Install Statuses',
        systemLogs: 'System Logs',
        emailSettings: 'Email Settings',
        manageNews: 'Manage News',
        autoReportSettings: 'Report Auto',
        // Auto Report Settings
        autoReportSettingsTitle: 'Auto Report Settings (Email Excel)',
        enableAutomatedEmails: 'Enable Automated Emails',
        frequency: 'Frequency',
        weeklyFrequency: 'Weekly (Every Monday at midnight)',
        monthlyFrequency: 'Monthly (1st of the month at midnight)',
        bothFrequency: 'Both (Weekly & Monthly)',
        weeklyDesc: 'Emails will be sent every Monday at 00:00 covering the previous Mon-Sun period.',
        monthlyDesc: 'Emails will be sent on the 1st day of every month at 00:00 covering the entire previous month.',
        bothDesc: 'Emails will be sent every Monday (Weekly report) AND on the 1st day of every month (Monthly report).',
        recipientsLabel: 'Recipients (Email Addresses)',
        recipientsPlaceholder: 'example@domain.com, admin2@domain.com',
        recipientsHelpText: 'Separate multiple email addresses with a comma (,)',
        saveSettings: 'Save Settings',
        // Attachment Settings
        attachmentSettings: 'Attachment Settings',
        enableAttachments: 'Enable File Attachments (Tickets & Chat)',
        maxFileSize: 'Max File Size (MB)',
        allowedExtensions: 'Allowed File Extensions',
        // Common
        search: 'Search',
        cancel: 'Cancel',
        save: 'Save',
        delete: 'Delete',
        confirm: 'Confirm',
        ok: 'OK',
        actions: 'Actions',
        status: 'Status',
        // Profile Settings
        profileSettings: 'Profile Settings',
        personalInfo: 'Personal Information',
        changePassword: 'Change Password',
        currentPassword: 'Current Password',
        newPassword: 'New Password',
        confirmPassword: 'Confirm New Password',
        updatePassword: 'Update Password',
        saveChanges: 'Save Changes',
        // Dashboard
        openRequests: 'Open Requests',
        inProgress: 'In Progress',
        closedJobs: 'Closed Jobs',
        total: 'Total',
        exportCsv: '📥 Export CSV',
        jobsPerIT: '📊 Jobs per IT Staff',
        problemsByCategory: '🏷️ Problems by Category',
        problemsByLocation: '📍 Problems by Location',
        ticketsBySite: '🏢 Tickets by Site',
        exportReport: '📥 Export Report to Excel (CSV)',
        fromDate: 'From Date',
        toDate: 'To Date',
        quickActions: 'Quick Actions',
        goToBoard: 'IT Request Board',
        viewHistory: 'View Closed History',
        supportChat: 'Support Chat',
        // Board
        getJob: 'Get Job',
        closeJob: 'Close Job',
        note: '📝 Note',
        chat: '💬 Chat',
        transfer: 'Transfer',
        ticketNo: 'Ticket No',
        requester: 'Requester',
        location: 'Location',
        date: 'Date',
        assignedTo: 'Assigned To',
        noActiveRequests: 'No active requests',
        // Approve
        approve: '✅ Approve',
        reject: '❌ Reject',
        pendingDesc: 'New members who register will appear here. Approve to grant access, or reject to remove.',
        noPendingUsers: 'No pending users.',
        name: 'Name',
        username: 'Username',
        email: 'Email',
        phone: 'Phone',
        company: 'Company',
        site: 'Site',
        department: 'Department',
        // Guest
        reportIssue: 'Report Issue',
        trackIssue: 'Track Your Issue',
        welcomeTitle: 'Welcome to IT Service',
        welcomeSub: 'Please select an option below to proceed.',
        registerMember: 'Register as Member',
        submitRepairTitle: 'Submit a Repair Request',
        locationLabel: 'Location *',
        selectLocation: '-- Select Location --',
        companyLabel: 'Company *',
        selectCompany: '-- Select Company --',
        siteLabel: 'Site *',
        selectSite: '-- Select Site --',
        departmentLabel: 'Department *',
        selectDepartment: '-- Select Department --',
        fullNameLabel: 'Full Name *',
        contactPhoneLabel: 'Contact Phone (Optional)',
        issueDetailsLabel: 'Issue Details *',
        issuePlaceholder: 'Describe your issue in detail...',
        resetBtn: 'Reset',
        submitRequestBtn: 'Submit Request',
        trackIssueTitle: 'Track Your Issue',
        searchPlaceholder: 'Enter Ticket No, Phone Number, or Name',
        searchBtn: 'Search',
        noTicketsFound: 'No tickets found. Enter a keyword to search.',
        ticketSuccess: 'Ticket successfully created:',
        failedSubmit: 'Failed to submit',
        serverError: 'Server connection error.',
        submitSuccess: 'Success!',
        submitAnother: 'Submit Another Request',
        // Register
        registerSuccess: 'Registration successful! Please wait for Admin approval.',
        registerFailed: 'Registration failed',
        memberRegistrationTitle: 'Member Registration',
        memberRegistrationSub: 'Complete the form below to request access.',
        firstNameLabel: 'First Name *',
        lastNameLabel: 'Last Name *',
        employeeIdLabel: 'Employee ID',
        companyEmailLabel: 'Company Email (Optional)',
        usernameLabel: 'Username *',
        passwordLabel: 'Password *',
        submitRegistrationBtn: 'Submit Registration Form',
        // User
        userMenu: 'User Menu',
        myProfile: 'My Profile',
        myIssues: 'Track My Issues',
        reportNewIssue: 'Report a New Issue',
        issueDetailsUserLabel: 'Issue Details *',
        issueDetailsUserPlaceholder: 'Describe your issue. Your location and department details will be automatically attached.',
        submitIssueBtn: 'Submit Issue',
        ticketCreatedSuccess: 'Ticket successfully created:',
        submitFailed: 'Failed to submit',
        serverConnectionError: 'Server connection error.',
        // User Track
        trackMyIssues: 'Track My Issues',
        dateTime: 'Date / Time',
        detail: '📋 Detail',
        noRecordedIssues: 'You have no recorded issues.',
        ticketDetail: 'Ticket Detail',
        created: 'Created',
        category: 'Category',
        closedAt: 'Closed At',
        issueDetails: 'Issue Details',
        solution: 'Solution',
        close: 'Close',
        pendingAssignment: 'Pending...',
        // User Chat
        myTickets: 'My Tickets',
        closed: 'Closed',
        noMessagesYet: 'No messages yet. Start the conversation!',
        you: 'You',
        itSupportLabel: 'IT Support',
        savedHistory: 'Saved History',
        ticketClosedReadOnly: 'This ticket is closed. Chat is read-only.',
        waitingForAssignment: 'Waiting for IT staff to accept this ticket. Chat will be available once assigned.',
        attachFiles: 'Attach Files',
        typeMessage: 'Type a message...',
        send: 'Send',
        selectTicketPrompt: 'Select a ticket from the left to view chat history.',
        attached: 'Attached',
        // User Profile
        editProfile: '✏️ Edit Profile',
        firstName: 'First Name',
        lastName: 'Last Name',
        changePasswordOptional: 'Change Password (Optional)',
        oldPassword: 'Old Password',
        requiredIfChanging: 'Required if changing',
        newPassword: 'New Password',
        saveProfile: '💾 Save Profile',
        role: 'Role',
        contact: 'Contact',
        noContactInfo: 'No contact info provided',
        profileUpdated: 'Profile updated successfully!',
        errorUpdatingProfile: 'Error updating profile',
        connectivityError: 'Connectivity error',
        orgDetailsNote: 'If you need to update your organizational details (Location, Company, Site, Department), please contact an Administrator.',
        // PC Inventory
        listComputer: 'List Computer',
        manageTrackAssets: 'Manage and track hardware assets.',
        searchInventory: 'Search by Asset No, Device Name, Emp ID...',
        addComputer: 'Add Computer',
        computerDetails: 'Computer Details',
        downloadQR: 'Download QR Code',
        pcAssetNo: 'PC Asset No',
        deviceName: 'Device Name',
        employeeId: 'Employee ID',
        employeeName: 'Employee Name',
        statusUsage: 'Status Usage',
        // Computer Form (Add & Edit)
        assignmentLocation: 'Assignment & Location',
        searchEmpId: 'Search Employee ID to Auto-fill',
        extNoPhone: 'Extension No. / Desk Phone',
        buildingName: 'Building Name',
        hardwareDetails: 'Hardware Details',
        deviceType: 'Device Type',
        selectType: 'Select Type',
        notebookBrandModel: 'Notebook Brand & Model',
        serialNumberSn: 'Serial Number (S/N)',
        statusPc: 'Status PC',
        active: 'Active',
        inactive: 'Inactive',
        specificationsSoftware: 'Specifications & Software',
        softwareDetails: 'Software Details',
        os: 'Operating System',
        selectOs: 'Select OS',
        windowsProductKey: 'Windows Product Key',
        msOffice: 'MS Office',
        selectOffice: 'Select Office',
        selectMsOffice: 'Select MS Office',
        networkAdditionalAssets: 'Network & Additional Assets',
        lifecycleDetails: 'Lifecycle Details',
        lifespanWarranty: 'Lifespan & Warranty',
        purchaseDate: 'Purchase Date',
        issueDate: 'Issue Date',
        deviceAgeAuto: 'Device Age (Auto-calculated)',
        deviceAge: 'Device Age',
        serviceLifeGroupAuto: 'Service Life Group (Auto)',
        serviceLifeGroup: 'Service Life Group',
        systemStatus: 'System & Status',
        cpuCore: 'CPU Core',
        egCpu: 'e.g. Intel Core i5-12400F',
        searchSuccess: 'Success',
        searchSuccessMsg: 'Employee data loaded.',
        searchNotFound: 'Not Found',
        searchNotFoundMsg: 'Employee not found in the system.',
        searchErrorMsg: 'Failed to search employee.',
        ramGb: 'RAM (GB)',
        egRam: 'e.g. 16GB',
        scriptInstallStatus: 'Script Install Status',
        selectStatus: 'Select Status',
        vpnStatus: 'VPN Status',
        backupStatus: 'Backup Status',
        yes: 'Yes',
        no: 'No',
        upsAssetNo: 'UPS Asset No.',
        accessories: 'Accessories',
        accessoriesPlaceholder: 'Mouse, Keyboard, Bag...',
        additionalNotes: 'Additional Notes',
        notes: 'Notes',
        addNote: 'Add Note',
        removeNote: 'Remove',
        confirmAddComputer: 'Confirm Add Computer',
        confirmAddComputerMsg: 'Are you sure you want to add this computer to the inventory?',
        updatePcDetails: 'Update PC Details',
        saveComputerToInventory: 'Save Computer To Inventory',
        // Admin Master & History
        siteName: 'Site Name',
        company: 'Company',
        companyName: 'Company Name',
        description: 'Description',
        categoryName: 'Category Name',
        duplicateData: 'Duplicate Data',
        alreadyExists: 'already exists in the system.',
        deleteUserConfirm: 'Confirm Deletion',
        deleteUserMsg: 'Are you sure you want to permanently delete this user?',
        deleteUserErrorRef: 'Cannot delete user because they have existing tickets or history. Please disable their status instead.',
        deptCode: 'Dept Code',
        deptName: 'Dept Name',
        locationName: 'Location Name',
        id: 'ID',
        manageSites: 'Manage Sites',
        manageCompanies: 'Manage Companies',
        manageLocations: 'Manage Locations',
        manageDepartments: 'Manage Departments',
        manageCategories: 'Manage Problem Categories',
        closedDate: 'Closed Date',
        problemCategory: 'Problem Category',
        assignedIt: 'Assigned IT',
        solutionNote: 'Solution Note',
    },
    th: {
        login: 'เข้าสู่ระบบ',
        loginBtn: 'เข้าสู่ระบบ',
        logout: 'ออกจากระบบ',
        register: 'สมัครสมาชิก',
        signInToContinue: 'เข้าสู่ระบบเพื่อดำเนินการต่อ',
        backToGuest: 'กลับสู่หน้าผู้ดูแล / ลูกค้า',
        // Top Nav Categories
        organizationCategory: 'องค์กร',
        serviceCategory: 'การจัดการบริการ',
        computerSettingsCategory: 'ตั้งค่าคอมพิวเตอร์',
        systemCategory: 'ระบบ',
        ticketsCategory: 'Tickets',
        supportCategory: 'สนับสนุน',
        // IT Sidebar
        itMenu: 'เมนู IT',
        dashboardStats: '📊 แดชบอร์ด',
        requestBoard: '📋 บอร์ดคำขอ',
        historyTickets: '🗄️ ประวัติ Ticket',
        computerInventory: '💻 ทะเบียนคอมพิวเตอร์',
        closeJobHistory: '✅ ประวัติงานที่ปิด',
        userApproval: 'อนุมัติผู้ใช้',
        itUsersChat: '💬 แชท IT/ผู้ใช้',
        // IT Pages
        itDashboard: 'แดชบอร์ด IT',
        itRequestBoard: 'บอร์ดคำขอ IT',
        closedJobHistory: 'ประวัติงานที่ปิดแล้ว',
        itSupportChat: 'แชทสนับสนุน IT',
        // Admin Sidebar
        adminMenu: 'เมนูผู้ดูแล',
        dashboard: 'แดชบอร์ด',
        locations: 'สถานที่',
        companies: 'บริษัท',
        sites: 'ไซต์',
        departments: 'แผนก',
        categories: 'หมวดหมู่',
        manageUsers: 'จัดการผู้ใช้',
        manageTickets: 'จัดการ Ticket',
        deviceTypes: 'ประเภทอุปกรณ์',
        operatingSystems: 'ระบบปฏิบัติการ',
        msOffices: 'ออฟฟิศ (MS Office)',
        serviceLifeGroups: 'กลุ่มอายุการใช้งาน',
        scriptInstallStatuses: 'สถานะการติดตั้งสคริปต์',
        systemLogs: 'ประวัติระบบ (Logs)',
        emailSettings: 'ตั้งค่าอีเมล',
        autoReportSettings: 'ส่งรายงานอัตโนมัติ',
        // Auto Report Settings
        autoReportSettingsTitle: 'ตั้งค่าส่งรายงานอัตโนมัติ (Email Excel)',
        enableAutomatedEmails: 'เปิดใช้งานส่งอีเมลอัตโนมัติ',
        frequency: 'ความถี่การส่ง',
        weeklyFrequency: 'รายสัปดาห์ (ทุกคืนวันจันทร์ 00:00 น.)',
        monthlyFrequency: 'รายเดือน (วันที่ 1 ของทุกเดือน 00:00 น.)',
        bothFrequency: 'ทั้งคู่ (รายสัปดาห์ & รายเดือน)',
        weeklyDesc: 'ระบบจะส่งอีเมลทุกวันจันทร์เวลา 00:00 น. โดยสรุปข้อมูลตั้งแต่วันจันทร์-อาทิตย์ ที่ผ่านมา',
        monthlyDesc: 'ระบบจะส่งอีเมลในวันที่ 1 ของทุกเดือนเวลา 00:00 น. โดยสรุปข้อมูลตลอดเดือนก่อนหน้า',
        bothDesc: 'ระบบจะส่งตามรอบทั้ง "รายสัปดาห์" และ "รายเดือน"',
        recipientsLabel: 'ผู้รับ (ที่อยู่อีเมล)',
        recipientsPlaceholder: 'example@domain.com, admin2@domain.com',
        recipientsHelpText: 'คั่นหลายอีเมลด้วยเครื่องหมายจุลภาค (,)',
        saveSettings: 'บันทึกการตั้งค่า',
        // Attachment Settings
        attachmentSettings: 'ตั้งค่าไฟล์แนบ',
        enableAttachments: 'เปิดใช้งานการแนบไฟล์ (Ticket และ Chat)',
        maxFileSize: 'ขนาดไฟล์สูงสุด (MB)',
        allowedExtensions: 'นามสกุลไฟล์ที่อนุญาต',
        // Common
        search: 'ค้นหา',
        cancel: 'ยกเลิก',
        save: 'บันทึก',
        delete: 'ลบ',
        confirm: 'ยืนยัน',
        ok: 'ตกลง',
        actions: 'การกระทำ',
        status: 'สถานะ',
        // Profile Settings
        profileSettings: 'ตั้งค่าโปรไฟล์',
        personalInfo: 'ข้อมูลส่วนตัว',
        changePassword: 'เปลี่ยนรหัสผ่าน',
        currentPassword: 'รหัสผ่านปัจจุบัน',
        newPassword: 'รหัสผ่านใหม่',
        confirmPassword: 'ยืนยันรหัสผ่านใหม่',
        updatePassword: 'อัปเดตรหัสผ่าน',
        saveChanges: 'บันทึกการเปลี่ยนแปลง',
        // Dashboard
        openRequests: 'งานที่รอรับ',
        inProgress: 'กำลังดำเนินการ',
        closedJobs: 'งานที่ปิดแล้ว',
        total: 'ทั้งหมด',
        exportCsv: '📥 ส่งออก CSV',
        jobsPerIT: '📊 งานรายคน IT',
        problemsByCategory: '🏷️ ปัญหาตามหมวดหมู่',
        problemsByLocation: '📍 ปัญหาตามสถานที่',
        ticketsBySite: '🏢 งานแจ้งซ่อมตาม Site',
        exportReport: '📥 ส่งออกรายงาน Excel (CSV)',
        fromDate: 'จากวันที่',
        toDate: 'ถึงวันที่',
        quickActions: 'การดำเนินการด่วน',
        goToBoard: 'IT Request Board',
        viewHistory: 'ดูประวัติงานที่ปิด',
        supportChat: 'แชทสนับสนุน',
        // Board
        getJob: 'รับงาน',
        closeJob: 'ปิดงาน',
        note: '📝 บันทึก',
        chat: '💬 แชท',
        transfer: 'โอนงาน',
        ticketNo: 'เลขที่ Ticket',
        requester: 'ผู้แจ้ง',
        location: 'สถานที่',
        date: 'วันที่',
        assignedTo: 'ผู้รับผิดชอบ',
        noActiveRequests: 'ไม่มีคำขอที่ใช้งาน',
        // Approve
        approve: '✅ อนุมัติ',
        reject: '❌ ปฏิเสธ',
        pendingDesc: 'สมาชิกใหม่ที่สมัครจะปรากฏที่นี่ กดอนุมัติเพื่ออนุญาตเข้าใช้ หรือปฏิเสธเพื่อลบ',
        noPendingUsers: 'ไม่มีผู้ใช้ที่รออนุมัติ',
        name: 'ชื่อ',
        username: 'ชื่อผู้ใช้',
        email: 'อีเมล',
        phone: 'เบอร์โทร',
        company: 'บริษัท',
        site: 'ไซต์',
        department: 'แผนก',
        // Guest
        reportIssue: 'แจ้งซ่อม',
        trackIssue: 'ติดตามงานซ่อม',
        welcomeTitle: 'ยินดีต้อนรับสู่บริการ IT',
        welcomeSub: 'กรุณาเลือกตัวเลือกด้านล่างเพื่อดำเนินการต่อ',
        registerMember: 'สมัครสมาชิก',
        submitRepairTitle: 'ยื่นคำร้องแจ้งซ่อม',
        locationLabel: 'สถานที่ *',
        selectLocation: '-- เลือกสถานที่ --',
        companyLabel: 'บริษัท *',
        selectCompany: '-- เลือกบริษัท --',
        siteLabel: 'ไซต์ *',
        selectSite: '-- เลือกไซต์ --',
        departmentLabel: 'แผนก *',
        selectDepartment: '-- เลือกแผนก --',
        fullNameLabel: 'ชื่อ-นามสกุล *',
        contactPhoneLabel: 'เบอร์ติดต่อ (ไม่บังคับ)',
        issueDetailsLabel: 'รายละเอียดปัญหา *',
        issuePlaceholder: 'อธิบายปัญหาของคุณโดยละเอียด...',
        resetBtn: 'ล้างค่า',
        submitRequestBtn: 'ส่งคำร้อง',
        trackIssueTitle: 'ติดตามปัญหาของคุณ',
        searchPlaceholder: 'กรอกเลขที่ Ticket, เบอร์โทรศัพท์, หรือชื่อ',
        searchBtn: 'ค้นหา',
        noTicketsFound: 'ไม่พบคำขอ กรุณากรอกคำค้นหา',
        ticketSuccess: 'สร้าง Ticket สำเร็จ:',
        failedSubmit: 'ส่งคำร้องล้มเหลว',
        serverError: 'ข้อผิดพลาดในการเชื่อมต่อเซิร์ฟเวอร์',
        submitSuccess: 'สำเร็จ!',
        submitAnother: 'ยื่นคำร้องใหม่อีกครั้ง',
        // Register
        registerSuccess: 'ลงทะเบียนสำเร็จ! กรุณารอผู้ดูแลระบบอนุมัติ',
        registerFailed: 'ลงทะเบียนไม่สำเร็จ',
        memberRegistrationTitle: 'สมัครสมาชิก',
        memberRegistrationSub: 'กรอกแบบฟอร์มด้านล่างเพื่อขอสิทธิ์เข้าใช้งาน',
        firstNameLabel: 'ชื่อ *',
        lastNameLabel: 'นามสกุล *',
        employeeIdLabel: 'รหัสพนักงาน',
        companyEmailLabel: 'อีเมลบริษัท (ไม่บังคับ)',
        usernameLabel: 'ชื่อผู้ใช้ *',
        passwordLabel: 'รหัสผ่าน *',
        submitRegistrationBtn: 'ส่งแบบฟอร์มสมัครสมาชิก',
        // User
        userMenu: 'เมนูผู้ใช้',
        myProfile: 'โปรไฟล์ของฉัน',
        myIssues: 'ติดตามงานซ่อมของฉัน',
        reportNewIssue: 'แจ้งปัญหาใหม่',
        issueDetailsUserLabel: 'รายละเอียดปัญหา *',
        issueDetailsUserPlaceholder: 'อธิบายปัญหาของคุณ ข้อมูลสถานที่และแผนกจะถูกแนบโดยอัตโนมัติ',
        submitIssueBtn: 'ส่งคำร้อง',
        ticketCreatedSuccess: 'สร้าง Ticket สำเร็จ:',
        submitFailed: 'ส่งคำร้องล้มเหลว',
        serverConnectionError: 'ข้อผิดพลาดในการเชื่อมต่อเซิร์ฟเวอร์',
        // User Track
        trackMyIssues: 'ติดตามงานซ่อมของฉัน',
        dateTime: 'วันที่ / เวลา',
        detail: '📋 รายละเอียด',
        noRecordedIssues: 'คุณยังไม่มีรายการแจ้งซ่อม',
        ticketDetail: 'รายละเอียด Ticket',
        created: 'วันที่สร้าง',
        category: 'หมวดหมู่',
        closedAt: 'วันที่ปิด',
        issueDetails: 'รายละเอียดปัญหา',
        solution: 'การแก้ไข',
        close: 'ปิด',
        pendingAssignment: 'รอดำเนินการ...',
        // User Chat
        myTickets: 'Ticket ของฉัน',
        closed: 'ปิดแล้ว',
        noMessagesYet: 'ยังไม่มีข้อความ เริ่มสนทนาเลย!',
        you: 'คุณ',
        itSupportLabel: 'ฝ่าย IT',
        savedHistory: 'บันทึกประวัติแล้ว',
        ticketClosedReadOnly: 'Ticket นี้ปิดแล้ว แชทอ่านได้อย่างเดียว',
        waitingForAssignment: 'รอเจ้าหน้าที่ IT รับงาน เมื่อมีคนรับงานแล้วจะสามารถแชทได้',
        attachFiles: 'แนบไฟล์',
        typeMessage: 'พิมพ์ข้อความ...',
        send: 'ส่ง',
        selectTicketPrompt: 'เลือก Ticket จากด้านซ้ายเพื่อดูประวัติแชท',
        attached: 'แนบไฟล์',
        // User Profile
        editProfile: '✏️ แก้ไขโปรไฟล์',
        firstName: 'ชื่อ',
        lastName: 'นามสกุล',
        changePasswordOptional: 'เปลี่ยนรหัสผ่าน (ไม่บังคับ)',
        oldPassword: 'รหัสผ่านเดิม',
        requiredIfChanging: 'จำเป็นหากต้องการเปลี่ยน',
        newPassword: 'รหัสผ่านใหม่',
        saveProfile: '💾 บันทึกโปรไฟล์',
        role: 'บทบาท',
        contact: 'ข้อมูลติดต่อ',
        noContactInfo: 'ไม่มีข้อมูลติดต่อ',
        profileUpdated: 'อัปเดตโปรไฟล์สำเร็จ!',
        errorUpdatingProfile: 'เกิดข้อผิดพลาดในการอัปเดตโปรไฟล์',
        connectivityError: 'ข้อผิดพลาดในการเชื่อมต่อ',
        orgDetailsNote: 'หากคุณต้องการอัปเดตข้อมูลองค์กร (สถานที่, บริษัท, ไซต์, แผนก) กรุณาติดต่อผู้ดูแลระบบ',
        // PC Inventory
        listComputer: 'รายการคอมพิวเตอร์',
        manageTrackAssets: 'จัดการและติดตามทรัพย์สินฮาร์ดแวร์คอมพิวเตอร์',
        searchInventory: 'ค้นหาด้วยรหัสทรัพย์สิน, ชื่ออุปกรณ์, รหัสพนักงาน...',
        addComputer: 'เพิ่มคอมพิวเตอร์',
        computerDetails: 'รายละเอียดคอมพิวเตอร์',
        downloadQR: 'ดาวน์โหลด QR Code',
        pcAssetNo: 'รหัสทรัพย์สิน PC',
        deviceName: 'ชื่ออุปกรณ์',
        employeeId: 'รหัสพนักงาน',
        employeeName: 'ชื่อพนักงาน',
        statusUsage: 'สถานะการใช้งาน',
        // Computer Form (Add & Edit)
        assignmentLocation: 'ข้อมูลผู้ครอบครองและสถานที่',
        searchEmpId: 'ค้นหารหัสพนักงานเพื่อดึงข้อมูลอัตโนมัติ',
        extNoPhone: 'เบอร์ต่อ / เบอร์โต๊ะ',
        buildingName: 'ชื่ออาคาร',
        hardwareDetails: 'ข้อมูลฮาร์ดแวร์',
        deviceType: 'ประเภทอุปกรณ์',
        selectType: 'เลือกประเภท',
        notebookBrandModel: 'ยี่ห้อและรุ่น (Notebook)',
        serialNumberSn: 'หมายเลขซีเรียล (S/N)',
        statusPc: 'สถานะคอมพิวเตอร์',
        active: 'ใช้งาน (Active)',
        inactive: 'ไม่ใช้งาน (Inactive)',
        specificationsSoftware: 'ข้อมูลสเปกและซอฟต์แวร์',
        softwareDetails: 'ข้อมูลซอฟต์แวร์',
        os: 'ระบบปฏิบัติการ',
        selectOs: 'เลือกระบบปฏิบัติการ',
        windowsProductKey: 'Product Key (Windows)',
        msOffice: 'โปรแกรม MS Office',
        selectOffice: 'เลือกออฟฟิศ',
        selectMsOffice: 'เลือก MS Office',
        networkAdditionalAssets: 'เครือข่ายและทรัพย์สินเพิ่มเติม',
        lifecycleDetails: 'ข้อมูลอายุการใช้งาน',
        lifespanWarranty: 'อายุขัยและการรับประกัน',
        purchaseDate: 'วันที่จัดซื้อ',
        issueDate: 'วันที่เบิกจ่าย',
        deviceAgeAuto: 'อายุการใช้งานของอุปกรณ์ (คำนวณอัตโนมัติ)',
        deviceAge: 'อายุการใช้งานอุปกรณ์',
        serviceLifeGroupAuto: 'กลุ่มอายุการใช้งาน (อัตโนมัติ)',
        serviceLifeGroup: 'กลุ่มอายุการใช้งาน',
        systemStatus: 'ระบบและสถานะอื่นๆ',
        cpuCore: 'จำนวนคอร์ CPU',
        egCpu: 'ตัวอย่าง: Intel Core i5-12400F',
        ramGb: 'ขนาด RAM (GB)',
        egRam: 'ตัวอย่าง: 16GB',
        scriptInstallStatus: 'สถานะการติดตั้ง Script',
        searchSuccess: 'สำเร็จ',
        searchSuccessMsg: 'ดึงข้อมูลพนักงานเรียบร้อยแล้ว',
        searchNotFound: 'ไม่พบข้อมูล',
        searchNotFoundMsg: 'ไม่พบพนักงานรหัสนี้ในระบบ',
        searchErrorMsg: 'ไม่สามารถค้นหาข้อมูลพนักงานได้',
        selectStatus: 'เลือกสถานะ',
        vpnStatus: 'สถานะ VPN',
        backupStatus: 'สถานะการ Backup',
        yes: 'มี (Yes)',
        no: 'ไม่มี (No)',
        upsAssetNo: 'รหัสทรัพย์สิน UPS',
        accessories: 'อุปกรณ์เสริม',
        accessoriesPlaceholder: 'เมาส์, คีย์บอร์ด, กระเป๋า...',
        additionalNotes: 'บันทึกเพิ่มเติม',
        notes: 'บันทึกเพิ่มเติม',
        addNote: 'เพิ่มบันทึก',
        removeNote: 'ลบ',
        confirmAddComputer: 'ยืนยันการเพิ่มคอมพิวเตอร์',
        confirmAddComputerMsg: 'คุณแน่ใจหรือไม่ว่าต้องการเพิ่มคอมพิวเตอร์เครื่องนี้เข้าสู่คลังสินทรัพย์ระบบ?',
        updatePcDetails: 'อัปเดตข้อมูลคอมพิวเตอร์',
        saveComputerToInventory: 'บันทึกคอมพิวเตอร์เข้าระบบ',
        // Admin Master & History
        siteName: 'ชื่อไซต์',
        company: 'บริษัท',
        companyName: 'ชื่อบริษัท',
        description: 'รายละเอียด',
        categoryName: 'ชื่อหมวดหมู่',
        duplicateData: 'ข้อมูลซ้ำ',
        alreadyExists: 'มีอยู่ในระบบแล้ว',
        deleteUserConfirm: 'ยืนยันการลบ',
        deleteUserMsg: 'คุณแน่ใจหรือไม่ว่าต้องการลบผู้ใช้งานคนนี้ออกจากระบบถาวร?',
        deleteUserErrorRef: 'ไม่สามารถลบผู้ใช้งานนี้ได้เนื่องจากมีการดำเนินงาน (ทิกเก็ต, แชท) ในระบบ ขอแนะนำให้ปิดสถานะการใช้งานแทน',
        deptCode: 'รหัสแผนก',
        deptName: 'ชื่อแผนก',
        locationName: 'ชื่อสถานที่',
        id: 'ไอดี',
        manageSites: 'จัดการไซต์',
        manageCompanies: 'จัดการบริษัท',
        manageLocations: 'จัดการสถานที่ตั้ง',
        manageDepartments: 'จัดการแผนก',
        manageCategories: 'จัดการหมวดหมู่ปัญหา',
        closedDate: 'วันที่ปิดงาน',
        problemCategory: 'หมวดหมู่ปัญหา',
        assignedIt: 'ไอทีที่รับผิดชอบ',
        manageNews: 'จัดการข่าวสาร',
        manageReports: 'รายงาน',
        autoReportSettings: 'รายงานอัตโนมัติ (Report Auto)',
        solutionNote: 'บันทึกการแก้ไข',
        // Auto Report Settings
        autoReportSettingsTitle: 'ตั้งค่ารายงานอัตโนมัติ (ส่ง Excel ทางอีเมล)',
        enableAutomatedEmails: 'เปิดใช้งานการส่งอีเมลอัตโนมัติ',
        frequency: 'ความถี่ในการส่ง',
        weeklyFrequency: 'รายสัปดาห์ (ทุกวันจันทร์เวลาเที่ยงคืน)',
        monthlyFrequency: 'รายเดือน (วันที่ 1 ของเดือนเวลาเที่ยงคืน)',
        bothFrequency: 'ทั้งคู่ (รายสัปดาห์และรายเดือน)',
        weeklyDesc: 'ระบบจะส่งอีเมลทุกวันจันทร์เวลา 00:00 น. โดยครอบคลุมข้อมูลตั้งแต่วันจันทร์-อาทิตย์ที่ผ่านมา',
        monthlyDesc: 'ระบบจะส่งอีเมลในวันที่ 1 ของทุกเดือนเวลา 00:00 น. โดยครอบคลุมข้อมูลของเดือนที่ผ่านมาทั้งเดือน',
        bothDesc: 'ระบบจะส่งอีเมลทั้งรายสัปดาห์ (ทุกวันวันจันทร์) และรายเดือน (ทุกวันที่ 1 ของเดือน)',
        recipientsLabel: 'ผู้รับ (ที่อยู่อีเมล)',
        recipientsPlaceholder: 'example@domain.com, admin2@domain.com',
        recipientsHelpText: 'คั่นอีเมลหลายอีเมลด้วยเครื่องหมายจุลภาค (,)',
        saveSettings: 'บันทึกการตั้งค่า',
    }
};

const LanguageContext = createContext();

export function useLanguage() {
    return useContext(LanguageContext);
}

export function LanguageProvider({ children }) {
    const [lang, setLang] = useState('en');

    useEffect(() => {
        const saved = localStorage.getItem('app_language');
        if (saved) setLang(saved);
    }, []);

    const toggleLang = () => {
        const next = lang === 'en' ? 'th' : 'en';
        setLang(next);
        localStorage.setItem('app_language', next);
    };

    const t = (key) => translations[lang]?.[key] || translations.en[key] || key;

    return (
        <LanguageContext.Provider value={{ lang, toggleLang, t }}>
            {children}
        </LanguageContext.Provider>
    );
}
